import React, { useEffect, useMemo, useState } from 'react';
import { CoursePage, LanguageMode, SectionFilterType } from '../types';
import { a2Chapters, a2Pages, a2Scenes, a2Units } from '../data/a2CourseData';
import { AppSidebar } from './AppSidebar';
import { DashboardNavbar } from './DashboardNavbar';
import { ModuleHeroCard } from './ModuleHeroCard';
import { VocabularySection } from './VocabularySection';
import { DialogueSection } from './DialogueSection';
import { TableSection } from './TableSection';
import { NumbersSection } from './NumbersSection';
import { PronunciationSection } from './PronunciationSection';
import { RuleCardSection } from './RuleCardSection';
import { ExerciseSection } from './ExerciseSection';
import { NavigationFooter } from './NavigationFooter';
import { GlobalAudioPlayerBar } from './GlobalAudioPlayerBar';
import { AudioSettingsModal } from './AudioSettingsModal';
import { CheatSheetModal } from './CheatSheetModal';
import { getPlaybackSpeed, subscribeSpeechState } from '../utils/speech';

export const A2CoursePage: React.FC = () => {
  const [pageNumber, setPageNumber] = useState(() => Number(localStorage.getItem('deutschklar_a2_page') || 1));
  const [languageMode, setLanguageMode] = useState<LanguageMode>(() => (localStorage.getItem('deutsch_lang_mode') as LanguageMode) || 'en');
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [filter, setFilter] = useState<SectionFilterType>('all');
  const [showTranslations, setShowTranslations] = useState(true);
  const [showCheatSheet, setShowCheatSheet] = useState(false);
  const [showAudioSettings, setShowAudioSettings] = useState(false);
  const [audioSpeed, setAudioSpeed] = useState(getPlaybackSpeed());
  const currentPage = useMemo(() => a2Pages.find((page) => page.pageNumber === pageNumber) || a2Pages[0], [pageNumber]);
  useEffect(() => { localStorage.setItem('deutschklar_a2_page', String(pageNumber)); setFilter('all'); window.scrollTo({ top: 0, behavior: 'smooth' }); }, [pageNumber]);
  useEffect(() => subscribeSpeechState((state) => setAudioSpeed(state.speed)), []);
  const showSection = (type: string) => filter === 'all' || (filter === 'vocab' && type === 'vocabulary') || (filter === 'grammar' && type === 'rule_card') || (filter === 'dialogue' && type === 'dialogue');
  const selectPage = (page: number) => setPageNumber(page);
  return <div className="study-shell min-h-screen text-slate-900 selection:bg-indigo-200 selection:text-slate-950 flex flex-row font-reading"><AppSidebar isOpen={sidebarOpen} onClose={() => setSidebarOpen(false)} currentChapterNumber={currentPage.chapterNumber} currentPageNumber={pageNumber} totalPages={a2Pages.length} onSelectChapter={(chapter) => selectPage(a2Chapters.find((item) => item.number === chapter)?.startPage || 1)} onSelectPage={selectPage} languageMode={languageMode} onLanguageChange={setLanguageMode} onOpenCheatSheet={() => setShowCheatSheet(true)} activeView="course" onSelectView={() => undefined} onOpenAudioSettings={() => setShowAudioSettings(true)} showTranslations={showTranslations} onToggleTranslations={() => setShowTranslations((value) => !value)} audioSpeed={audioSpeed} onSpeedChange={setAudioSpeed} courseUnitsOverride={a2Units} chaptersOverride={a2Chapters} pagesOverride={a2Pages} scenesOverride={a2Scenes} /><div className="flex-1 min-w-0 flex flex-col min-h-screen"><DashboardNavbar isSidebarOpen={sidebarOpen} onToggleSidebar={() => setSidebarOpen((value) => !value)} currentPage={currentPage} totalPages={a2Pages.length} languageMode={languageMode} activeView="course" onSelectView={() => undefined} courseUnitsOverride={a2Units} chaptersOverride={a2Chapters} /><main className={`flex-1 w-full mx-auto px-4 sm:px-8 lg:px-12 py-8 space-y-8 transition-all duration-300 ${sidebarOpen ? 'max-w-5xl' : 'max-w-6xl'}`}><ModuleHeroCard currentPage={currentPage} languageMode={languageMode} onSelectFilter={setFilter} /><div className="space-y-6">{currentPage.sections.map((section) => !showSection(section.type) ? null : <div key={section.id}>{section.type === 'vocabulary' && <VocabularySection section={section} languageMode={languageMode} showTranslations={showTranslations} />}{section.type === 'dialogue' && <DialogueSection section={section} languageMode={languageMode} showTranslations={showTranslations} />}{section.type === 'table' && <TableSection section={section} languageMode={languageMode} showTranslations={showTranslations} />}{section.type === 'numbers' && <NumbersSection section={section} languageMode={languageMode} />}{section.type === 'pronunciation' && <PronunciationSection section={section} languageMode={languageMode} />}{section.type === 'rule_card' && <RuleCardSection section={section} languageMode={languageMode} />}</div>)}</div>{(filter === 'all' || filter === 'exercises') && currentPage.exercises.length > 0 && <div id="section-exercises" className="space-y-5 pt-4"><div className="flex items-center gap-2.5 pb-3 border-b border-slate-200"><span className="w-2.5 h-2.5 rounded-full bg-slate-800" /><h2 className="font-bold text-slate-900 text-xl tracking-tight">Übungen zum Modul</h2><span className="text-xs font-semibold px-2.5 py-0.5 rounded-lg bg-slate-100 text-slate-700 border border-slate-200">{currentPage.exercises.length} Aufgaben</span></div>{currentPage.exercises.map((exercise) => <ExerciseSection key={exercise.id} exercise={exercise} languageMode={languageMode} pageId={currentPage.pageNumber} />)}</div>}<NavigationFooter currentPage={currentPage} allPages={a2Pages} chapters={a2Chapters} onSelectPage={selectPage} languageMode={languageMode} /></main></div><GlobalAudioPlayerBar /><AudioSettingsModal isOpen={showAudioSettings} onClose={() => setShowAudioSettings(false)} languageMode={languageMode} /><CheatSheetModal isOpen={showCheatSheet} onClose={() => setShowCheatSheet(false)} languageMode={languageMode} /></div>;
};
