import React, { useMemo, useState } from 'react';
import { ArrowRight, BookOpen, Check, ChevronRight, Search, Sparkles } from 'lucide-react';
import { PrimaryNavigation } from './PrimaryNavigation';

type Lesson = { id: string; category: string; title: string; lead: string; rule: string; examples: { de: string; en: string; note?: string }[]; terms: string[] };

const lessons: Lesson[] = [
  { id: 'cases', category: 'Kasus', title: 'Die vier Fälle verstehen', lead: 'Fälle zeigen, welche Rolle ein Nomen im Satz spielt.', rule: 'Wer? = Nominativ · Wen/was? = Akkusativ · Wem? = Dativ · Wessen? = Genitiv', examples: [{ de: 'Der Mann sieht den Hund.', en: 'The man sees the dog.', note: 'Der Mann handelt. Den Hund sieht er.' }, { de: 'Ich gebe dem Kind den Ball.', en: 'I give the child the ball.', note: 'dem Kind = Empfänger · den Ball = Sache' }, { de: 'Das Auto meines Bruders ist neu.', en: 'My brother’s car is new.', note: 'meines Bruders = Besitz' }], terms: ['Nominativ', 'Akkusativ', 'Dativ', 'Genitiv', 'den', 'dem'] },
  { id: 'articles', category: 'Artikel', title: 'der · die · das richtig lernen', lead: 'Lerne jedes Nomen direkt mit seinem Artikel und seiner Pluralform.', rule: 'Maskulin: der · Feminin: die · Neutrum: das · Plural: die', examples: [{ de: 'der Tisch → die Tische', en: 'the table → the tables' }, { de: 'die Lampe → die Lampen', en: 'the lamp → the lamps' }, { de: 'das Fenster → die Fenster', en: 'the window → the windows' }], terms: ['der', 'die', 'das', 'ein', 'eine', 'kein'] },
  { id: 'pronouns', category: 'Pronomen', title: 'ich · mich · mir', lead: 'Pronomen verändern sich je nach ihrer Rolle im Satz.', rule: 'ich → mich → mir · du → dich → dir · er → ihn → ihm', examples: [{ de: 'Ich sehe ihn.', en: 'I see him.', note: 'Wen sehe ich? Akkusativ.' }, { de: 'Ich helfe ihm.', en: 'I help him.', note: 'Wem helfe ich? Dativ.' }, { de: 'Sie gibt mir das Buch.', en: 'She gives me the book.' }], terms: ['ich', 'mich', 'mir', 'dich', 'ihm', 'ihnen'] },
  { id: 'verbs', category: 'Verben', title: 'Verben im Alltag', lead: 'Konjugation, Modalverben, trennbare und reflexive Verben.', rule: 'Das konjugierte Verb steht im Hauptsatz meistens auf Position 2.', examples: [{ de: 'Ich muss heute arbeiten.', en: 'I have to work today.', note: 'Modalverb auf Position 2, Infinitiv am Ende.' }, { de: 'Ich stehe um sieben Uhr auf.', en: 'I get up at seven.', note: 'aufstehen trennt sich.' }, { de: 'Ich interessiere mich für Musik.', en: 'I am interested in music.', note: 'sich interessieren = reflexives Verb.' }], terms: ['sein', 'haben', 'werden', 'müssen', 'aufstehen', 'sich'] },
  { id: 'word-order', category: 'Satzbau', title: 'Wo steht das Verb?', lead: 'Baue klare Sätze mit Zeit, Fragen, Modalverben und Nebensätzen.', rule: 'Hauptsatz: Verb auf 2 · Ja/Nein-Frage: Verb auf 1 · Nebensatz: Verb am Ende', examples: [{ de: 'Heute lerne ich Deutsch.', en: 'Today I am learning German.' }, { de: 'Lernst du heute Deutsch?', en: 'Are you learning German today?' }, { de: 'Ich bleibe zu Hause, weil ich krank bin.', en: 'I stay home because I am ill.' }], terms: ['Position 2', 'Frage', 'weil', 'dass', 'Verb am Ende'] },
  { id: 'tenses', category: 'Zeitformen', title: 'Präsens, Perfekt & Zukunft', lead: 'Sprich über jetzt, früher und morgen mit klaren Satzmustern.', rule: 'Perfekt: haben/sein + Partizip II · Futur: werden + Infinitiv', examples: [{ de: 'Ich lerne Deutsch.', en: 'I am learning German.' }, { de: 'Ich habe Deutsch gelernt.', en: 'I learned German.' }, { de: 'Ich werde morgen arbeiten.', en: 'I will work tomorrow.' }, { de: 'Ich war zu Hause.', en: 'I was at home.' }], terms: ['Präsens', 'Perfekt', 'Präteritum', 'Futur'] },
  { id: 'prepositions', category: 'Präpositionen', title: 'WO oder WOHIN?', lead: 'Bei Wechselpräpositionen entscheidet die Bewegung über den Kasus.', rule: 'WO? → Dativ · WOHIN? → Akkusativ', examples: [{ de: 'Ich bin in der Küche.', en: 'I am in the kitchen.', note: 'WO? Ort, keine Bewegung.' }, { de: 'Ich gehe in die Küche.', en: 'I go into the kitchen.', note: 'WOHIN? Bewegung.' }, { de: 'Ich fahre mit dem Bus.', en: 'I travel by bus.', note: 'mit + Dativ.' }], terms: ['mit', 'für', 'in', 'auf', 'zu', 'WO', 'WOHIN'] },
  { id: 'negation', category: 'Negation', title: 'nicht oder kein?', lead: 'Verneine Verben, Adjektive und Nomen sicher.', rule: 'kein steht vor einem Nomen ohne bestimmten Artikel · nicht verneint die Handlung oder Eigenschaft', examples: [{ de: 'Ich habe kein Auto.', en: 'I do not have a car.', note: 'Auto = Nomen.' }, { de: 'Ich fahre nicht.', en: 'I am not driving.', note: 'fahren = Handlung.' }, { de: 'Das ist nicht teuer.', en: 'That is not expensive.' }], terms: ['nicht', 'kein', 'keine', 'nichts', 'niemand', 'nie'] },
  { id: 'adjectives', category: 'Adjektive', title: 'gut · besser · am besten', lead: 'Vergleiche Personen und Dinge und erkenne die wichtigsten Endungen.', rule: 'Komparativ: -er · Superlativ: am ...-sten', examples: [{ de: 'Dieses Buch ist gut.', en: 'This book is good.' }, { de: 'Dieses Buch ist besser.', en: 'This book is better.' }, { de: 'Das ist das beste Buch.', en: 'That is the best book.' }, { de: 'Ich sehe einen guten Film.', en: 'I am watching a good film.', note: 'einen + guten im Akkusativ.' }], terms: ['gut', 'besser', 'am besten', 'guten', 'groß', 'größer'] },
  { id: 'connectors', category: 'Satzverbindungen', title: 'weil · dass · wenn · obwohl', lead: 'Verbinde deine Gedanken und stelle das Verb richtig.', rule: 'und/aber: normale Wortstellung · weil/dass/wenn/obwohl: Verb am Ende · deshalb: Verb auf 2', examples: [{ de: 'Ich lerne, weil ich in Deutschland lebe.', en: 'I study because I live in Germany.' }, { de: 'Ich weiß, dass er kommt.', en: 'I know that he is coming.' }, { de: 'Es regnet. Trotzdem gehe ich raus.', en: 'It is raining. Nevertheless, I go outside.' }], terms: ['und', 'aber', 'denn', 'weil', 'dass', 'wenn', 'obwohl', 'deshalb'] },
  { id: 'questions', category: 'Fragen', title: 'W-Fragen im Alltag', lead: 'Finde schnell die richtige Frage für Ort, Zeit, Grund und Person.', rule: 'wer = Person · was = Sache · wo = Ort · wohin = Richtung · warum = Grund', examples: [{ de: 'Wer kommt heute?', en: 'Who is coming today?' }, { de: 'Wohin gehst du?', en: 'Where are you going?' }, { de: 'Warum lernst du Deutsch?', en: 'Why are you learning German?' }], terms: ['wer', 'was', 'wo', 'wohin', 'woher', 'wann', 'warum', 'wie'] },
  { id: 'time', category: 'Zeit & Datum', title: 'am · um · im · seit', lead: 'Sprich natürlich über Uhrzeit, Tage, Monate und Zeiträume.', rule: 'um 8 Uhr · am Montag · im Mai · seit zwei Jahren · für drei Tage', examples: [{ de: 'Der Kurs beginnt um neun Uhr.', en: 'The course starts at nine.' }, { de: 'Am Montag lerne ich.', en: 'I study on Monday.' }, { de: 'Ich wohne seit zwei Jahren hier.', en: 'I have lived here for two years.' }], terms: ['am', 'um', 'im', 'seit', 'für', 'vor', 'nach'] },
];

const caseRows = [['Nominativ', 'der', 'die', 'das', 'die'], ['Akkusativ', 'den', 'die', 'das', 'die'], ['Dativ', 'dem', 'der', 'dem', 'den'], ['Genitiv', 'des', 'der', 'des', 'der']];
const pronounRows = [['ich', 'mich', 'mir'], ['du', 'dich', 'dir'], ['er', 'ihn', 'ihm'], ['sie', 'sie', 'ihr'], ['es', 'es', 'ihm'], ['wir', 'uns', 'uns'], ['ihr', 'euch', 'euch'], ['sie/Sie', 'sie/Sie', 'ihnen/Ihnen']];

export const GrammarPage: React.FC = () => {
  const [query, setQuery] = useState('');
  const [selected, setSelected] = useState<Lesson | null>(lessons[0]);
  const [answer, setAnswer] = useState<string | null>(null);
  const filtered = useMemo(() => lessons.filter((lesson) => `${lesson.title} ${lesson.category} ${lesson.lead} ${lesson.terms.join(' ')}`.toLowerCase().includes(query.toLowerCase())), [query]);
  return <div className="min-h-screen bg-[#f7f9fc] text-slate-900 font-reading">
    <header className="sticky top-0 z-30 border-b border-slate-200/80 bg-white/85 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><a href="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-slate-950 text-sm font-black text-white">DK</span><span><span className="block text-sm font-black tracking-tight">DeutschKlar</span><span className="block text-[11px] text-slate-500">Grammatik-Library</span></span></a><PrimaryNavigation active="grammar" /></div></header>
    <main className="mx-auto max-w-7xl px-5 pb-20">
      <section className="relative overflow-hidden py-16 sm:py-24"><div className="absolute -right-24 -top-20 h-72 w-72 rounded-full bg-indigo-200/40 blur-3xl" /><div className="relative max-w-3xl"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-indigo-100 bg-white px-3 py-1.5 text-xs font-bold text-indigo-700 shadow-sm"><Sparkles className="h-4 w-4" /> A1 → A2 Grammar Library</div><h1 className="text-5xl font-black tracking-[-0.055em] text-slate-950 sm:text-7xl">German Grammar.<br /><span className="text-indigo-600">Alles klar.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Verstehe die wichtigsten Regeln Schritt für Schritt – mit klaren Beispielen, Übersetzungen und kurzen Übungen, die wirklich hängen bleiben.</p><div className="relative mt-9 max-w-2xl"><Search className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Was möchtest du verstehen? z. B. mich, den, weil ..." className="h-14 w-full rounded-2xl border border-slate-200 bg-white pl-12 pr-5 text-sm shadow-lg shadow-slate-200/40 outline-none transition focus:border-indigo-400 focus:ring-4 focus:ring-indigo-100" /></div></div></section>
      <section className="mb-14"><div className="mb-5 flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-indigo-600">Schnellstart</p><h2 className="mt-2 text-2xl font-black tracking-tight">Was möchtest du heute klären?</h2></div><span className="text-sm text-slate-500">{filtered.length} Themen</span></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((lesson) => <button key={lesson.id} onClick={() => { setSelected(lesson); setAnswer(null); }} className="group rounded-3xl border border-slate-200 bg-white p-5 text-left shadow-sm transition hover:-translate-y-1 hover:border-indigo-200 hover:shadow-xl hover:shadow-indigo-100/40"><div className="flex items-center justify-between"><span className="rounded-full bg-indigo-50 px-2.5 py-1 text-[11px] font-black uppercase tracking-wider text-indigo-700">{lesson.category}</span><ArrowRight className="h-5 w-5 text-slate-300 transition group-hover:translate-x-1 group-hover:text-indigo-600" /></div><h3 className="mt-5 text-xl font-black tracking-tight">{lesson.title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{lesson.lead}</p><div className="mt-5 flex flex-wrap gap-1.5">{lesson.terms.slice(0, 4).map((term) => <span key={term} className="rounded-lg bg-slate-50 px-2 py-1 text-xs text-slate-600">{term}</span>)}</div></button>)}</div></section>
      <section className="mb-14 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="mb-6 flex items-center gap-3"><BookOpen className="h-5 w-5 text-indigo-600" /><div><h2 className="font-black">Artikel & Fälle auf einen Blick</h2><p className="text-sm text-slate-500">Der wichtigste Spickzettel</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[520px] text-left text-sm"><thead><tr className="border-b border-slate-100 text-xs uppercase tracking-wider text-slate-400"><th className="p-3">Kasus</th><th className="p-3">Maskulin</th><th className="p-3">Feminin</th><th className="p-3">Neutrum</th><th className="p-3">Plural</th></tr></thead><tbody>{caseRows.map((row, i) => <tr key={row[0]} className="border-b border-slate-50 last:border-0"><td className="p-3 font-bold text-indigo-700">{row[0]}</td>{row.slice(1).map((cell) => <td key={cell + i} className="p-3 text-lg font-black text-slate-800">{cell}</td>)}</tr>)}</tbody></table></div></div><div className="rounded-3xl bg-slate-950 p-6 text-white shadow-xl shadow-slate-300/30 sm:p-8"><p className="text-xs font-black uppercase tracking-[0.2em] text-indigo-300">Merksatz</p><h2 className="mt-4 text-3xl font-black tracking-tight">Wer macht was<br />mit wem?</h2><div className="mt-7 space-y-4 text-sm"><div className="rounded-2xl bg-white/10 p-4"><b className="text-indigo-300">Wer?</b><span className="ml-3">Der Mann handelt.</span></div><div className="rounded-2xl bg-white/10 p-4"><b className="text-indigo-300">Wen?</b><span className="ml-3">Er sieht den Hund.</span></div><div className="rounded-2xl bg-white/10 p-4"><b className="text-indigo-300">Wem?</b><span className="ml-3">Er hilft dem Kind.</span></div></div></div></section>
      <section className="mb-14 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="mb-6"><p className="text-xs font-black uppercase tracking-[0.2em] text-indigo-600">Pronomen</p><h2 className="mt-2 text-2xl font-black">ich → mich → mir</h2><p className="mt-2 text-sm text-slate-500">Nominativ · Akkusativ · Dativ</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{pronounRows.map((row) => <div key={row[0]} className="rounded-2xl bg-slate-50 p-4"><div className="grid grid-cols-3 gap-2 text-center"><span className="font-black text-slate-900">{row[0]}</span><span className="font-black text-indigo-600">{row[1]}</span><span className="font-black text-emerald-600">{row[2]}</span></div><div className="mt-2 grid grid-cols-3 text-center text-[10px] uppercase tracking-wider text-slate-400"><span>wer</span><span>wen</span><span>wem</span></div></div>)}</div></section>
      <section><div className="mb-5"><p className="text-xs font-black uppercase tracking-[0.2em] text-indigo-600">Mini-Praxis</p><h2 className="mt-2 text-2xl font-black">Teste dein Gefühl</h2></div><div className="rounded-3xl border border-indigo-100 bg-indigo-50/70 p-6 sm:p-8"><p className="text-sm font-bold text-indigo-900">Welche Form ist richtig?</p><p className="mt-4 text-2xl font-black text-slate-950">Ich helfe ___ Mann.</p><div className="mt-6 flex flex-wrap gap-3">{['der', 'den', 'dem'].map((option) => <button key={option} onClick={() => setAnswer(option)} className={`rounded-xl border px-6 py-3 text-sm font-black transition ${answer === option ? option === 'dem' ? 'border-emerald-500 bg-emerald-500 text-white' : 'border-rose-400 bg-rose-50 text-rose-700' : 'border-white bg-white text-slate-700 hover:border-indigo-300'}`}>{option}</button>)}</div>{answer && <p className={`mt-4 flex items-center gap-2 text-sm font-bold ${answer === 'dem' ? 'text-emerald-700' : 'text-rose-700'}`}>{answer === 'dem' ? <Check className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />} {answer === 'dem' ? 'Richtig: helfen verlangt den Dativ.' : 'Fast – helfen fragt: Wem? → dem Mann.'}</p>}</div></section>
    </main>
    {selected && <section className="mt-10 grid gap-6 lg:grid-cols-[220px_1fr]"><aside className="rounded-3xl border border-slate-200 bg-white p-3 shadow-sm"><p className="px-3 py-3 text-xs font-black uppercase tracking-[0.18em] text-slate-400">Lektion wählen</p>{lessons.map((lesson) => <button key={lesson.id} onClick={() => { setSelected(lesson); setAnswer(null); }} className={`mb-1 w-full rounded-2xl px-3 py-3 text-left transition ${selected.id === lesson.id ? 'bg-slate-950 text-white shadow-lg' : 'text-slate-600 hover:bg-slate-50'}`}><span className="block text-[10px] font-black uppercase tracking-wider opacity-60">{lesson.category}</span><span className="mt-1 block text-sm font-bold">{lesson.title}</span></button>)}</aside><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-10"><div className="flex flex-wrap items-start justify-between gap-5"><div><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-black uppercase tracking-wider text-indigo-700">{selected.category}</span><h2 className="mt-4 text-3xl font-black tracking-tight">{selected.title}</h2><p className="mt-2 max-w-2xl text-slate-500">{selected.lead}</p></div><span className="rounded-2xl bg-slate-100 px-3 py-2 text-xs font-bold text-slate-500">Explain → Example → Practice</span></div><div className="mt-8 grid gap-4 md:grid-cols-2"><div className="rounded-2xl bg-indigo-50 p-5"><p className="text-xs font-black uppercase tracking-wider text-indigo-600">Schnellregel</p><p className="mt-2 text-lg font-black leading-7 text-indigo-950">{selected.rule}</p></div><div className="rounded-2xl bg-amber-50 p-5"><p className="text-xs font-black uppercase tracking-wider text-amber-700">Warum?</p><p className="mt-2 text-sm leading-6 text-amber-950">Frage zuerst nach der Rolle im Satz. Das Verb zeigt oft, ob du nach „wen/was“ oder „wem“ fragst.</p></div></div><div className="mt-9"><h3 className="text-lg font-black">Beispiele im Kontext</h3><div className="mt-4 grid gap-3">{selected.examples.map((example, index) => <div key={example.de} className="grid gap-2 rounded-2xl border border-slate-200 p-4 sm:grid-cols-[28px_1fr]"><span className="grid h-7 w-7 place-items-center rounded-full bg-slate-950 text-xs font-black text-white">{index + 1}</span><div><p className="text-lg font-black text-slate-900">{example.de}</p><p className="mt-1 text-sm font-medium text-indigo-700">{example.en}</p>{example.note && <p className="mt-2 text-xs text-slate-500">{example.note}</p>}</div></div>)}</div></div><div className="mt-9 rounded-2xl bg-slate-950 p-5 text-white"><p className="text-xs font-black uppercase tracking-wider text-indigo-300">Mini-Merksatz</p><p className="mt-2 text-sm leading-6 text-slate-200">Lies die Beispiele laut und tausche danach ein Wort aus. So lernst du die Struktur, nicht nur die Regel.</p></div></article></section>}
  </div>;
};
