import React from 'react';
import { ArrowRight, BookOpen, Headphones, Sparkles, Library, FileText, MessageCircle, ChevronRight, Play, Volume2 } from 'lucide-react';
import { PrimaryNavigation } from './PrimaryNavigation';

export const LandingPage: React.FC = () => (
  <div className="min-h-screen overflow-hidden bg-[#f7f9fd] text-slate-950">
    <header className="absolute inset-x-0 top-0 z-20 mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8 lg:px-12"><a href="/" className="flex items-center gap-3 text-white"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-slate-950 text-sm font-black shadow-xl">DE</span><span><strong className="block text-sm tracking-tight">Deutsch Lernen</strong><small className="block text-[11px] text-white/65">A1 Sprachstudio</small></span></a><PrimaryNavigation className="rounded-2xl bg-white/90 p-1 shadow-lg backdrop-blur-md" /></header>
    <main>
      <section className="relative isolate min-h-[720px] overflow-hidden bg-slate-950"><img src="/images/landing-hero.png" alt="Moderner Lernplatz für Deutsch" className="absolute inset-0 -z-20 h-full w-full object-cover object-center opacity-75" /><div className="absolute inset-0 -z-10 bg-gradient-to-r from-slate-950 via-slate-950/75 to-slate-950/15" /><div className="mx-auto grid min-h-[720px] max-w-7xl items-center gap-8 px-5 pb-14 pt-28 sm:px-8 lg:grid-cols-[1fr_0.9fr] lg:px-12"><div className="max-w-xl text-white"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-xs font-bold text-indigo-100 backdrop-blur"><Sparkles className="h-3.5 w-3.5" /> Klar lernen. Sicher sprechen.</div><h1 className="text-5xl font-black tracking-[-0.04em] sm:text-7xl sm:leading-[0.98]">Deutsch wird<br /><span className="text-indigo-300">klarer.</span></h1><p className="mt-6 max-w-lg text-base leading-8 text-white/75 sm:text-lg">Ein ruhiger A1-Lernraum für echte Alltagssituationen — mit Kurs, Audio, Geschichten und Wortschatz an einem Ort.</p><div className="mt-8 flex flex-wrap gap-3"><a href="/kurs" className="inline-flex items-center gap-2 rounded-2xl bg-indigo-500 px-5 py-3.5 text-sm font-bold text-white shadow-xl shadow-indigo-950/30 transition hover:bg-indigo-400"><Play className="h-4 w-4 fill-current" /> A1 Kurs starten</a><a href="/wortschatz" className="inline-flex items-center gap-2 rounded-2xl border border-white/20 bg-white/10 px-5 py-3.5 text-sm font-bold text-white backdrop-blur transition hover:bg-white/20">Wortschatz entdecken <ArrowRight className="h-4 w-4" /></a></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-xs font-medium text-white/55"><span>✓ Kostenlos</span><span>✓ Keine Anmeldung</span><span>✓ Mit Audio</span></div></div><div className="relative hidden min-h-[430px] lg:block"><div className="absolute inset-8 rounded-[3rem] bg-indigo-500/20 blur-3xl" /><img src="/images/landing-study-cards.png" alt="Deutsche Lernkarten mit Wörtern und Sätzen" className="absolute right-[-14%] top-1/2 w-[125%] max-w-none -translate-y-1/2 drop-shadow-2xl" /></div></div></section>
      <section className="relative z-10 mx-auto -mt-10 max-w-7xl px-5 sm:px-8 lg:px-12"><div className="grid overflow-hidden rounded-3xl border border-slate-200/80 bg-white/90 shadow-xl shadow-slate-900/10 backdrop-blur md:grid-cols-3"><Stat icon={<BookOpen />} value="15" label="Kapitel im A1-Kurs" /><Stat icon={<Volume2 />} value="350+" label="Wörter mit Audio" /><Stat icon={<MessageCircle />} value="100%" label="Für Alltagssituationen" /></div></section>
      <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-12"><div className="mb-8 flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-indigo-600">Dein Lernstudio</p><h2 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Alles, was du heute brauchst.</h2><p className="mt-3 text-sm text-slate-500">Wähle einen Bereich und leg direkt los.</p></div><span className="hidden text-xs font-bold text-slate-400 sm:block">A1 · Deutsch für jeden Tag</span></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><HubCard href="/kurs" icon={<BookOpen />} tone="indigo" eyebrow="01 · Struktur" title="A1 Lehrbuch" text="Dialoge, Grammatik und Übungen — Schritt für Schritt." /><HubCard href="/geschichten" icon={<Headphones />} tone="violet" eyebrow="02 · Hören" title="Hörgeschichten" text="Kurze Geschichten mit Audio zum Mitlesen und Verstehen." /><HubCard href="/wortschatz" icon={<Library />} tone="amber" eyebrow="03 · Wörter" title="Wortschatz" text="Viele Alltagsthemen mit Übersetzung und Aussprache." /><HubCard href="/kurs" icon={<FileText />} tone="emerald" eyebrow="04 · Klarheit" title="Grammatik" text="Kasus, Satzbau und Grundregeln einfach nachschlagen." /></div></section>
      <section className="relative overflow-hidden bg-white"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-16 sm:px-8 lg:grid-cols-[1fr_1.15fr] lg:items-center lg:px-12"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-indigo-600">Deine Werkzeuge</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Lernen, wie es zu dir passt.</h2><p className="mt-4 max-w-md text-sm leading-7 text-slate-500">Wähle deinen nächsten Schritt: ein Kapitel, eine Geschichte, ein Wortschatzthema oder eine schnelle Grammatik-Hilfe.</p><div className="mt-7 flex flex-wrap gap-3"><a href="/kurs" className="rounded-2xl bg-slate-950 px-4 py-3 text-sm font-bold text-white transition hover:bg-indigo-700">Kapitel öffnen</a><a href="/geschichten" className="rounded-2xl border border-slate-200 px-4 py-3 text-sm font-bold text-slate-800 transition hover:border-indigo-300">Audio hören</a></div></div><div className="relative min-h-[230px]"><div className="absolute inset-x-0 top-1/2 h-40 -translate-y-1/2 rounded-[2rem] bg-indigo-50" /><img src="/images/landing-learning-objects.png" alt="Lernbuch, Kopfhörer, Wortschatzkarten und A1-Notizbuch" className="relative z-10 w-full object-contain drop-shadow-xl" /></div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:px-12"><div className="rounded-[2rem] bg-indigo-600 px-6 py-10 text-white shadow-xl shadow-indigo-200 sm:px-10 lg:flex lg:items-center lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-indigo-200">Bereit?</p><h2 className="mt-2 text-3xl font-black tracking-tight">Dein Deutschkurs wartet.</h2><p className="mt-2 text-sm text-indigo-100">Starte ohne Konto und lerne in deinem Tempo.</p></div><a href="/kurs" className="mt-6 inline-flex w-fit items-center gap-2 rounded-2xl bg-white px-5 py-3.5 text-sm font-bold text-indigo-700 transition hover:bg-indigo-50 lg:mt-0">Kurs öffnen <ChevronRight className="h-4 w-4" /></a></div></section>
    </main><footer className="border-t border-slate-200 px-5 py-7 text-center text-xs text-slate-400">Deutsch Lernen · Dein klarer Weg zu Deutsch A1</footer>
  </div>
);

const Stat: React.FC<{ icon: React.ReactNode; value: string; label: string }> = ({ icon, value, label }) => <div className="flex items-center gap-3 border-b border-slate-100 p-5 last:border-0 md:border-b-0 md:border-r md:last:border-0"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-50 text-indigo-600">{React.cloneElement(icon as React.ReactElement, { className: 'h-5 w-5' })}</span><span><strong className="block text-xl font-black">{value}</strong><small className="block text-xs text-slate-500">{label}</small></span></div>;
const HubCard: React.FC<{ href: string; icon: React.ReactNode; tone: string; eyebrow: string; title: string; text: string }> = ({ href, icon, tone, eyebrow, title, text }) => <a href={href} className="group rounded-3xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:border-indigo-200 hover:shadow-xl"><span className={`flex h-11 w-11 items-center justify-center rounded-2xl ${tone === 'indigo' ? 'bg-indigo-50 text-indigo-600' : tone === 'violet' ? 'bg-violet-50 text-violet-600' : tone === 'amber' ? 'bg-amber-50 text-amber-600' : 'bg-emerald-50 text-emerald-600'}`}>{React.cloneElement(icon as React.ReactElement, { className: 'h-5 w-5' })}</span><p className="mt-5 text-[11px] font-bold uppercase tracking-widest text-slate-400">{eyebrow}</p><h3 className="mt-2 text-xl font-black tracking-tight">{title}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-slate-500">{text}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-slate-900">Öffnen <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></a>;
