import React from 'react';
import { ArrowRight, BookOpen, Headphones, Library, Play, Volume2, Check } from 'lucide-react';
import { PrimaryNavigation } from './PrimaryNavigation';

const destinations = [
  { href: '/kurs', icon: BookOpen, eyebrow: 'COURSE', title: 'A1 Lehrbuch', text: 'A complete beginner pathway with lessons, dialogues, grammar and exercises.', color: 'text-blue-700 bg-blue-50', image: '/images/landing-grammar.png' },
  { href: '/geschichten', icon: Headphones, eyebrow: 'LISTENING', title: 'Hörgeschichten', text: 'Short German stories with audio, readable transcripts and translations.', color: 'text-violet-700 bg-violet-50' },
  { href: '/wortschatz', icon: Library, eyebrow: 'VOCABULARY', title: 'Wortschatz', text: 'Practical everyday vocabulary organised by clear, useful themes.', color: 'text-amber-700 bg-amber-50', image: '/images/landing-vocabulary-cards.png' },
];

export const LandingPage: React.FC = () => (
  <div className="min-h-screen bg-[#f5f7fa] text-[#172033]">
    <header className="border-b border-slate-200/80 bg-white/80 backdrop-blur-xl"><div className="mx-auto flex h-[76px] max-w-7xl items-center justify-between px-5 sm:px-8 lg:px-12"><a href="/" className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#172033] text-sm font-bold text-white">DE</span><span><strong className="block text-sm font-semibold tracking-[-0.01em]">Deutsch Lernen</strong><small className="block text-[11px] text-slate-500">A1 Sprachstudio</small></span></a><PrimaryNavigation /></div></header>
    <main>
      <section className="border-b border-slate-200/80 bg-white"><div className="mx-auto grid max-w-7xl items-center gap-14 px-5 py-16 sm:px-8 lg:grid-cols-[0.95fr_1.05fr] lg:px-12 lg:py-24"><div className="max-w-xl"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-700">German learning, made clear</p><h1 className="mt-5 text-5xl font-semibold leading-[1.05] tracking-[-0.055em] text-[#172033] sm:text-6xl">Build confidence in German, one clear lesson at a time.</h1><p className="mt-6 max-w-lg text-base leading-8 text-slate-600">A focused A1 learning platform for practical German — combining structured lessons, listening practice, vocabulary and essential grammar.</p><div className="mt-8 flex flex-wrap items-center gap-3"><a href="/kurs" className="inline-flex items-center gap-2 rounded-xl bg-[#172033] px-5 py-3.5 text-sm font-semibold text-white shadow-lg shadow-slate-900/10 transition hover:bg-blue-700">Start the A1 course <ArrowRight className="h-4 w-4" /></a><a href="/geschichten" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-5 py-3.5 text-sm font-semibold text-slate-700 transition hover:border-slate-300 hover:shadow-sm"><Play className="h-4 w-4" /> Explore listening</a></div><p className="mt-5 text-xs text-slate-400">Free to use · No account required</p></div><div className="relative min-h-[390px] overflow-hidden rounded-[2rem] bg-[#e9f1f8] p-6 sm:p-10"><div className="absolute -right-20 -top-24 h-72 w-72 rounded-full bg-white/70 blur-2xl" /><div className="absolute bottom-0 left-0 h-44 w-44 rounded-full bg-blue-200/40 blur-3xl" /><div className="relative z-10 flex h-full items-center justify-center"><img src="/images/landing-workbook.png" alt="German learning workbook" className="w-[78%] max-w-[360px] -rotate-6 drop-shadow-2xl" /><div className="absolute bottom-5 right-4 rounded-2xl border border-white/80 bg-white/75 px-4 py-3 shadow-lg backdrop-blur-xl sm:right-8"><span className="flex items-center gap-2 text-xs font-semibold text-slate-700"><Volume2 className="h-4 w-4 text-blue-700" /> Audio included</span></div></div></div></div></section>
      <section className="border-b border-slate-200/80 bg-[#f8fafc]"><div className="mx-auto grid max-w-7xl divide-y divide-slate-200/80 px-5 sm:grid-cols-3 sm:divide-x sm:divide-y-0 sm:px-8 lg:px-12"><Metric value="15" label="structured A1 chapters" /><Metric value="350+" label="vocabulary entries" /><Metric value="4" label="learning areas" /></div></section>
      <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-12"><div className="mb-9 max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-700">The platform</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">Everything you need to begin well.</h2><p className="mt-3 text-base leading-7 text-slate-500">A simple structure that keeps the important parts of language learning close at hand.</p></div><div className="grid gap-5 lg:grid-cols-3">{destinations.map(({ href, icon: Icon, eyebrow, title, text, color, image }) => <a key={title} href={href} className="group relative overflow-hidden rounded-3xl border border-white/80 bg-white/65 p-6 shadow-[0_8px_30px_rgba(23,32,51,0.04)] backdrop-blur-xl transition hover:-translate-y-0.5 hover:bg-white hover:shadow-[0_16px_40px_rgba(23,32,51,0.09)]"><span className={`relative z-10 flex h-11 w-11 items-center justify-center rounded-xl ${color}`}><Icon className="h-5 w-5" /></span>{image && <img src={image} alt="" className="absolute -right-5 -top-6 h-32 w-32 object-contain opacity-20 transition duration-500 group-hover:scale-105 group-hover:opacity-35" />}<p className="relative z-10 mt-8 text-[11px] font-semibold tracking-[0.16em] text-slate-400">{eyebrow}</p><h3 className="relative z-10 mt-2 text-xl font-semibold tracking-[-0.02em]">{title}</h3><p className="relative z-10 mt-3 min-h-14 text-sm leading-6 text-slate-500">{text}</p><span className="relative z-10 mt-6 inline-flex items-center gap-2 text-sm font-semibold text-[#172033]">Open area <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></a>)}</div></section>
      <section className="bg-[#172033] text-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[0.8fr_1.2fr] lg:items-center lg:px-12"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-300">A calmer way to learn</p><h2 className="mt-4 text-3xl font-semibold leading-tight tracking-[-0.04em] sm:text-4xl">Clear content.<br />Useful German.</h2><p className="mt-5 max-w-sm text-sm leading-7 text-slate-300">Designed for learners who want a focused place to practise without distractions.</p></div><div className="grid gap-3 sm:grid-cols-2"><Benefit text="Practical everyday language" /><Benefit text="Audio for pronunciation" /><Benefit text="Translations when you need them" /><Benefit text="No sign-up or paywall" /></div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:px-12"><div className="flex flex-col items-start justify-between gap-6 rounded-3xl border border-slate-200 bg-white p-7 shadow-sm sm:flex-row sm:items-center sm:p-10"><div><h2 className="text-2xl font-semibold tracking-[-0.03em]">Ready to start with A1?</h2><p className="mt-2 text-sm text-slate-500">Open the course and begin with the first lesson.</p></div><a href="/kurs" className="inline-flex items-center gap-2 rounded-xl bg-blue-700 px-5 py-3.5 text-sm font-semibold text-white transition hover:bg-blue-800">Open A1 course <ArrowRight className="h-4 w-4" /></a></div></section>
    </main><footer className="border-t border-slate-200/80 bg-white px-5 py-8 text-center text-xs text-slate-400">Deutsch Lernen · A focused German learning platform</footer>
  </div>
);

const Metric: React.FC<{ value: string; label: string }> = ({ value, label }) => <div className="flex items-center gap-4 py-5 sm:px-7 sm:py-7 first:sm:pl-0"><strong className="text-2xl font-semibold tracking-[-0.04em]">{value}</strong><span className="text-sm text-slate-500">{label}</span></div>;
const Benefit: React.FC<{ text: string }> = ({ text }) => <div className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.06] p-4 text-sm text-slate-200"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-blue-500/20 text-blue-300"><Check className="h-3.5 w-3.5" /></span>{text}</div>;
