import React from 'react';
import { ArrowRight, BookOpen, Headphones, Languages, Sparkles } from 'lucide-react';

export const LandingPage: React.FC = () => (
  <div className="landing-page min-h-screen bg-[#f5f8ff] text-slate-900">
    <header className="absolute inset-x-0 top-0 z-20 mx-auto flex items-center justify-between px-5 py-5 text-white sm:px-8 lg:px-12">
      <a href="/" className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl border border-white/50 bg-slate-950/75 text-sm font-black text-white shadow-lg backdrop-blur-md">DE</span><span><span className="block text-sm font-extrabold tracking-tight drop-shadow">Deutsch Lernen</span><span className="block text-[11px] text-white/75">A1 Sprachstudio</span></span></a>
      <nav className="flex items-center gap-2 text-sm font-bold"><a href="/geschichten" className="hidden rounded-xl border border-white/40 bg-white/15 px-4 py-2.5 text-white backdrop-blur-md transition hover:bg-white/25 sm:inline-flex">Geschichten</a><a href="/kurs" className="inline-flex items-center gap-2 rounded-xl bg-slate-950/85 px-4 py-2.5 text-white shadow-lg backdrop-blur-md transition hover:bg-indigo-700">Kurs öffnen <ArrowRight className="h-4 w-4" /></a></nav>
    </header>
    <main>
      <section className="relative isolate min-h-[760px] overflow-hidden"><img src="/images/landing-hero.png" alt="Moderner Lernplatz für Deutsch" className="absolute inset-0 -z-20 h-full w-full object-cover object-center" /><div className="absolute inset-0 -z-10 bg-gradient-to-r from-slate-950/75 via-slate-950/35 to-transparent" /><div className="mx-auto flex min-h-[760px] max-w-7xl items-center px-5 pb-12 pt-32 sm:px-8 lg:px-12"><div className="max-w-xl text-white"><div className="mb-5 inline-flex items-center gap-2 text-xs font-bold text-indigo-100"><Sparkles className="h-3.5 w-3.5" /> Klar lernen. Sicher sprechen.</div><h1 className="text-4xl font-black tracking-tight drop-shadow-lg sm:text-6xl sm:leading-[1.04]">Deutsch lernen, das sich leicht anfühlt.</h1><p className="mt-6 max-w-lg text-base leading-8 text-white/85 sm:text-lg">Ein ruhiger, klarer A1-Deutschkurs für echte Alltagssituationen — mit verständlichen Erklärungen, Audio und interaktiven Übungen.</p><div className="mt-8 flex flex-wrap gap-3"><a href="/kurs" className="inline-flex items-center gap-2 rounded-2xl bg-indigo-600 px-5 py-3.5 text-sm font-bold text-white shadow-xl shadow-slate-950/20 transition hover:bg-indigo-500">A1 Kurs starten <ArrowRight className="h-4 w-4" /></a><a href="/geschichten" className="inline-flex items-center gap-2 rounded-2xl border border-white/40 bg-white/15 px-5 py-3.5 text-sm font-bold text-white backdrop-blur-md transition hover:bg-white/25"><Headphones className="h-4 w-4" /> Geschichten hören</a></div><p className="mt-5 text-xs font-medium text-white/65">Kostenlos starten · Keine Anmeldung erforderlich</p></div></div></section>
      <section className="border-y border-slate-200/70 bg-white/55"><div className="mx-auto grid max-w-7xl gap-4 px-5 py-7 sm:grid-cols-3 sm:px-8"><Feature icon={<BookOpen />} title="Strukturiert" text="Kapitel für Kapitel durch A1." /><Feature icon={<Headphones />} title="Mit Audio" text="Hören, nachsprechen und sicherer werden." /><Feature icon={<Languages />} title="Mehrsprachig" text="Deutsch mit Arabisch, Englisch oder Französisch." /></div></section>
      <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:py-24"><div className="grid gap-6 lg:grid-cols-2"><a href="/kurs" className="group rounded-3xl border border-slate-200/80 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><p className="text-xs font-bold uppercase tracking-widest text-indigo-600">A1 Lehrbuch</p><h2 className="mt-3 text-2xl font-black tracking-tight">Lerne die Grundlagen mit System.</h2><p className="mt-3 text-sm leading-7 text-slate-600">Wortschatz, Dialoge, Grammatik, Aussprache und Übungen — alles in einem ruhigen Lernfluss.</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-slate-900">Zum Kurs <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></a><a href="/geschichten" className="group rounded-3xl border border-slate-200/80 bg-slate-950 p-7 text-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><p className="text-xs font-bold uppercase tracking-widest text-indigo-300">Hörgeschichten</p><h2 className="mt-3 text-2xl font-black tracking-tight">Deutsch im Kontext erleben.</h2><p className="mt-3 text-sm leading-7 text-slate-300">Kurze Lesestücke mit Satz-für-Satz-Audio und Übersetzungen zum entspannten Üben.</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-white">Geschichten öffnen <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></a></div></section>
    </main><footer className="border-t border-slate-200/70 px-5 py-6 text-center text-xs text-slate-400">Deutsch Lernen · Dein ruhiger Weg zu Deutsch A1</footer>
  </div>
);

const Feature: React.FC<{ icon: React.ReactNode; title: string; text: string }> = ({ icon, title, text }) => <div className="flex items-start gap-3 rounded-2xl p-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-indigo-50 text-indigo-600">{React.cloneElement(icon as React.ReactElement, { className: 'h-5 w-5' })}</span><div><h3 className="text-sm font-extrabold">{title}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div></div>;
