import React, { useState } from 'react';
import { ArrowLeft, BookOpen, BriefcaseBusiness, Carrot, GraduationCap, Home, Library, Pause, ShoppingBasket, TramFront, UserRound, Utensils, Volume2 } from 'lucide-react';
import { LanguageMode } from '../types';
import { speakGerman, stopSpeech } from '../utils/speech';

const translations: Record<string, { en: string; fr: string; ar: string }> = {
  'der Schreibtisch': { en: 'desk', fr: 'bureau', ar: 'مكتب' }, 'der Computer': { en: 'computer', fr: 'ordinateur', ar: 'حاسوب' }, 'der Bildschirm': { en: 'screen', fr: 'écran', ar: 'شاشة' }, 'die Tastatur': { en: 'keyboard', fr: 'clavier', ar: 'لوحة المفاتيح' }, 'die Maus': { en: 'mouse', fr: 'souris', ar: 'فأرة' }, 'der Drucker': { en: 'printer', fr: 'imprimante', ar: 'طابعة' }, 'das Telefon': { en: 'phone', fr: 'téléphone', ar: 'هاتف' }, 'die E-Mail': { en: 'email', fr: 'e-mail', ar: 'بريد إلكتروني' }, 'der Termin': { en: 'appointment', fr: 'rendez-vous', ar: 'موعد' }, 'die Pause': { en: 'break', fr: 'pause', ar: 'استراحة' },
  'das Brot': { en: 'bread', fr: 'pain', ar: 'خبز' }, 'der Käse': { en: 'cheese', fr: 'fromage', ar: 'جبن' }, 'die Suppe': { en: 'soup', fr: 'soupe', ar: 'حساء' }, 'der Reis': { en: 'rice', fr: 'riz', ar: 'أرز' }, 'das Fleisch': { en: 'meat', fr: 'viande', ar: 'لحم' }, 'der Fisch': { en: 'fish', fr: 'poisson', ar: 'سمك' }, 'das Ei': { en: 'egg', fr: 'œuf', ar: 'بيضة' }, 'das Wasser': { en: 'water', fr: 'eau', ar: 'ماء' }, 'die Milch': { en: 'milk', fr: 'lait', ar: 'حليب' }, 'der Kaffee': { en: 'coffee', fr: 'café', ar: 'قهوة' },
  'der Apfel': { en: 'apple', fr: 'pomme', ar: 'تفاحة' }, 'die Banane': { en: 'banana', fr: 'banane', ar: 'موزة' }, 'die Orange': { en: 'orange', fr: 'orange', ar: 'برتقالة' }, 'die Birne': { en: 'pear', fr: 'poire', ar: 'كمثرى' }, 'die Traube': { en: 'grape', fr: 'raisin', ar: 'عنب' }, 'die Erdbeere': { en: 'strawberry', fr: 'fraise', ar: 'فراولة' }, 'die Zitrone': { en: 'lemon', fr: 'citron', ar: 'ليمون' }, 'die Kirsche': { en: 'cherry', fr: 'cerise', ar: 'كرز' },
  'die Schule': { en: 'school', fr: 'école', ar: 'مدرسة' }, 'der Lehrer': { en: 'teacher', fr: 'professeur', ar: 'معلّم' }, 'der Schüler': { en: 'student', fr: 'élève', ar: 'تلميذ' }, 'das Buch': { en: 'book', fr: 'livre', ar: 'كتاب' }, 'das Heft': { en: 'notebook', fr: 'cahier', ar: 'دفتر' }, 'der Stift': { en: 'pen', fr: 'stylo', ar: 'قلم' }, 'die Aufgabe': { en: 'exercise', fr: 'exercice', ar: 'تمرين' }, 'die Prüfung': { en: 'exam', fr: 'examen', ar: 'امتحان' },
  'das Haus': { en: 'house', fr: 'maison', ar: 'منزل' }, 'die Wohnung': { en: 'apartment', fr: 'appartement', ar: 'شقة' }, 'das Zimmer': { en: 'room', fr: 'chambre', ar: 'غرفة' }, 'die Küche': { en: 'kitchen', fr: 'cuisine', ar: 'مطبخ' }, 'das Bad': { en: 'bathroom', fr: 'salle de bains', ar: 'حمّام' }, 'der Tisch': { en: 'table', fr: 'table', ar: 'طاولة' }, 'der Stuhl': { en: 'chair', fr: 'chaise', ar: 'كرسي' }, 'das Bett': { en: 'bed', fr: 'lit', ar: 'سرير' }, 'die Tür': { en: 'door', fr: 'porte', ar: 'باب' }, 'das Fenster': { en: 'window', fr: 'fenêtre', ar: 'نافذة' },
  'der Laden': { en: 'shop', fr: 'magasin', ar: 'متجر' }, 'der Supermarkt': { en: 'supermarket', fr: 'supermarché', ar: 'سوبرماركت' }, 'der Preis': { en: 'price', fr: 'prix', ar: 'سعر' }, 'das Geld': { en: 'money', fr: 'argent', ar: 'مال' }, 'die Kasse': { en: 'checkout', fr: 'caisse', ar: 'صندوق الدفع' }, 'die Tasche': { en: 'bag', fr: 'sac', ar: 'حقيبة' }, 'kaufen': { en: 'to buy', fr: 'acheter', ar: 'يشتري' }, 'bezahlen': { en: 'to pay', fr: 'payer', ar: 'يدفع' },
  'der Bus': { en: 'bus', fr: 'bus', ar: 'حافلة' }, 'der Zug': { en: 'train', fr: 'train', ar: 'قطار' }, 'das Fahrrad': { en: 'bicycle', fr: 'vélo', ar: 'دراجة' }, 'das Auto': { en: 'car', fr: 'voiture', ar: 'سيارة' }, 'der Bahnhof': { en: 'station', fr: 'gare', ar: 'محطة' }, 'die Straße': { en: 'street', fr: 'rue', ar: 'شارع' }, 'das Ticket': { en: 'ticket', fr: 'billet', ar: 'تذكرة' }, 'links': { en: 'left', fr: 'gauche', ar: 'يسار' }, 'rechts': { en: 'right', fr: 'droite', ar: 'يمين' },
  'der Kopf': { en: 'head', fr: 'tête', ar: 'رأس' }, 'das Auge': { en: 'eye', fr: 'œil', ar: 'عين' }, 'das Ohr': { en: 'ear', fr: 'oreille', ar: 'أذن' }, 'die Nase': { en: 'nose', fr: 'nez', ar: 'أنف' }, 'der Mund': { en: 'mouth', fr: 'bouche', ar: 'فم' }, 'die Hand': { en: 'hand', fr: 'main', ar: 'يد' }, 'der Arm': { en: 'arm', fr: 'bras', ar: 'ذراع' }, 'das Bein': { en: 'leg', fr: 'jambe', ar: 'ساق' },
};

const englishTranslations: Record<string, string> = {
  'das Papier': 'paper', 'der Ordner': 'folder', 'die Datei': 'file', 'das Dokument': 'document', 'die Besprechung': 'meeting', 'der Kalender': 'calendar', 'der Kollege': 'colleague', 'die Kollegin': 'female colleague', 'der Chef': 'boss', 'die Abteilung': 'department', 'arbeiten': 'to work', 'schreiben': 'to write', 'drucken': 'to print', 'telefonieren': 'to make a phone call',
  'das Brötchen': 'bread roll', 'die Butter': 'butter', 'die Nudeln': 'pasta', 'das Gemüse': 'vegetables', 'der Salat': 'salad', 'der Saft': 'juice', 'der Tee': 'tea', 'der Zucker': 'sugar', 'das Salz': 'salt', 'der Teller': 'plate', 'die Gabel': 'fork', 'das Messer': 'knife', 'essen': 'to eat', 'trinken': 'to drink',
  'die Mandarine': 'mandarin', 'der Pfirsich': 'peach', 'die Melone': 'melon', 'die Wassermelone': 'watermelon', 'die Ananas': 'pineapple', 'die Mango': 'mango', 'die Kiwi': 'kiwi', 'die Feige': 'fig', 'die Pflaume': 'plum', 'die Himbeere': 'raspberry', 'die Blaubeere': 'blueberry', 'süß': 'sweet', 'frisch': 'fresh', 'reif': 'ripe', 'schälen': 'to peel', 'schneiden': 'to cut',
  'die Klasse': 'class', 'die Lehrerin': 'female teacher', 'die Schülerin': 'female student', 'der Bleistift': 'pencil', 'der Radiergummi': 'eraser', 'das Lineal': 'ruler', 'der Rucksack': 'backpack', 'die Tafel': 'board', 'der Stundenplan': 'timetable', 'die Hausaufgabe': 'homework', 'die Note': 'grade', 'lernen': 'to learn', 'lesen': 'to read', 'rechnen': 'to calculate',
  'das Wohnzimmer': 'living room', 'das Schlafzimmer': 'bedroom', 'der Flur': 'hallway', 'der Balkon': 'balcony', 'der Schrank': 'cupboard', 'das Sofa': 'sofa', 'die Lampe': 'lamp', 'der Fernseher': 'television', 'der Kühlschrank': 'fridge', 'die Waschmaschine': 'washing machine', 'der Schlüssel': 'key', 'putzen': 'to clean', 'kochen': 'to cook', 'wohnen': 'to live',
  'der Markt': 'market', 'das Geschäft': 'shop', 'der Einkaufswagen': 'shopping cart', 'der Korb': 'basket', 'der Beutel': 'bag', 'der Bon': 'receipt', 'die Rechnung': 'bill', 'die Karte': 'card', 'das Angebot': 'offer', 'die Größe': 'size', 'die Farbe': 'colour', 'die Kleidung': 'clothing', 'der Kunde': 'customer', 'die Kundin': 'female customer', 'kosten': 'to cost', 'suchen': 'to search',
  'die Bahn': 'railway', 'die Straßenbahn': 'tram', 'das Taxi': 'taxi', 'das Flugzeug': 'plane', 'die Haltestelle': 'stop', 'die Kreuzung': 'intersection', 'die Ampel': 'traffic light', 'der Fahrplan': 'timetable', 'der Koffer': 'suitcase', 'der Weg': 'way', 'geradeaus': 'straight ahead', 'fahren': 'to travel', 'laufen': 'to walk', 'ankommen': 'to arrive',
  'das Gesicht': 'face', 'der Zahn': 'tooth', 'der Hals': 'neck', 'die Schulter': 'shoulder', 'der Finger': 'finger', 'der Bauch': 'stomach', 'der Rücken': 'back', 'das Knie': 'knee', 'der Fuß': 'foot', 'das Herz': 'heart', 'die Haut': 'skin', 'die Haare': 'hair', 'gesund': 'healthy', 'krank': 'ill', 'weh tun': 'to hurt', 'helfen': 'to help',
  'das Hemd': 'shirt', 'die Bluse': 'blouse', 'das T-Shirt': 'T-shirt', 'der Pullover': 'sweater', 'die Jacke': 'jacket', 'der Mantel': 'coat', 'die Hose': 'trousers', 'der Rock': 'skirt', 'das Kleid': 'dress', 'die Jeans': 'jeans', 'der Schuh': 'shoe', 'die Socke': 'sock', 'der Hut': 'hat', 'die Mütze': 'cap', 'der Schal': 'scarf', 'der Gürtel': 'belt', 'die Brille': 'glasses', 'rot': 'red', 'blau': 'blue', 'groß': 'big', 'klein': 'small', 'tragen': 'to wear', 'anziehen': 'to put on',
  'die Sonne': 'sun', 'die Wolke': 'cloud', 'der Regen': 'rain', 'der Schnee': 'snow', 'der Wind': 'wind', 'der Sturm': 'storm', 'der Himmel': 'sky', 'der Regenschirm': 'umbrella', 'der Frühling': 'spring', 'der Sommer': 'summer', 'der Herbst': 'autumn', 'der Winter': 'winter', 'warm': 'warm', 'kalt': 'cold', 'regnen': 'to rain',
  'die Familie': 'family', 'die Mutter': 'mother', 'der Vater': 'father', 'das Kind': 'child', 'das Baby': 'baby', 'der Freund': 'friend', 'die Freundin': 'female friend', 'der Nachbar': 'neighbour', 'die Nachbarin': 'female neighbour', 'die Großmutter': 'grandmother', 'der Großvater': 'grandfather', 'der Geburtstag': 'birthday', 'besuchen': 'to visit', 'sprechen': 'to speak',
  'die Musik': 'music', 'der Fußball': 'football', 'das Schwimmen': 'swimming', 'das Wandern': 'hiking', 'der Film': 'film', 'die Kamera': 'camera', 'das Kochen': 'cooking', 'das Zeichnen': 'drawing', 'das Tanzen': 'dancing', 'der Park': 'park', 'spielen': 'to play', 'hören': 'to listen',
  'das Restaurant': 'restaurant', 'das Café': 'café', 'der Kellner': 'waiter', 'die Speisekarte': 'menu', 'die Reservierung': 'reservation', 'das Frühstück': 'breakfast', 'das Mittagessen': 'lunch', 'das Abendessen': 'dinner', 'der Nachtisch': 'dessert', 'bestellen': 'to order', 'servieren': 'to serve',
};

const groups = [
  { title: 'Im Büro', icon: BriefcaseBusiness, image: '/images/vocab-office.png', color: 'bg-indigo-50 text-indigo-700', words: ['der Schreibtisch', 'der Computer', 'der Bildschirm', 'die Tastatur', 'die Maus', 'der Drucker', 'das Papier', 'der Ordner', 'die Datei', 'das Dokument', 'das Telefon', 'die E-Mail', 'der Termin', 'die Besprechung', 'der Kalender', 'der Kollege', 'die Kollegin', 'der Chef', 'die Abteilung', 'die Pause', 'arbeiten', 'schreiben', 'drucken', 'telefonieren'] },
  { title: 'Essen & Trinken', icon: Utensils, image: '/images/vocab-food.png', color: 'bg-orange-50 text-orange-700', words: ['das Brot', 'das Brötchen', 'der Käse', 'die Butter', 'die Suppe', 'der Reis', 'die Nudeln', 'das Fleisch', 'der Fisch', 'das Ei', 'das Gemüse', 'der Salat', 'das Wasser', 'die Milch', 'der Saft', 'der Kaffee', 'der Tee', 'der Zucker', 'das Salz', 'der Teller', 'die Gabel', 'das Messer', 'essen', 'trinken'] },
  { title: 'Obst', icon: Carrot, image: '/images/vocab-fruit.png', color: 'bg-rose-50 text-rose-700', words: ['der Apfel', 'die Banane', 'die Orange', 'die Mandarine', 'die Birne', 'die Traube', 'die Erdbeere', 'die Zitrone', 'die Kirsche', 'der Pfirsich', 'die Melone', 'die Wassermelone', 'die Ananas', 'die Mango', 'die Kiwi', 'die Feige', 'die Pflaume', 'die Himbeere', 'die Blaubeere', 'süß', 'frisch', 'reif', 'schälen', 'schneiden'] },
  { title: 'In der Schule', icon: GraduationCap, image: '/images/vocab-school.png', color: 'bg-sky-50 text-sky-700', words: ['die Schule', 'die Klasse', 'der Lehrer', 'die Lehrerin', 'der Schüler', 'die Schülerin', 'das Buch', 'das Heft', 'der Stift', 'der Bleistift', 'der Radiergummi', 'das Lineal', 'der Rucksack', 'die Tafel', 'der Tisch', 'der Stundenplan', 'die Aufgabe', 'die Hausaufgabe', 'die Prüfung', 'die Note', 'lernen', 'lesen', 'schreiben', 'rechnen'] },
  { title: 'Zu Hause', icon: Home, image: '/images/vocab-home.png', color: 'bg-emerald-50 text-emerald-700', words: ['das Haus', 'die Wohnung', 'das Zimmer', 'das Wohnzimmer', 'das Schlafzimmer', 'die Küche', 'das Bad', 'der Flur', 'der Balkon', 'der Tisch', 'der Stuhl', 'das Bett', 'der Schrank', 'das Sofa', 'die Lampe', 'der Fernseher', 'der Kühlschrank', 'die Waschmaschine', 'die Tür', 'das Fenster', 'der Schlüssel', 'putzen', 'kochen', 'wohnen'] },
  { title: 'Einkaufen', icon: ShoppingBasket, image: '/images/vocab-shopping.png', color: 'bg-violet-50 text-violet-700', words: ['der Laden', 'der Supermarkt', 'der Markt', 'das Geschäft', 'der Preis', 'das Geld', 'die Kasse', 'der Einkaufswagen', 'der Korb', 'die Tasche', 'der Beutel', 'der Bon', 'die Rechnung', 'die Karte', 'das Angebot', 'die Größe', 'die Farbe', 'die Kleidung', 'der Kunde', 'die Kundin', 'kaufen', 'bezahlen', 'kosten', 'suchen'] },
  { title: 'Unterwegs', icon: TramFront, image: '/images/vocab-transport.png', color: 'bg-teal-50 text-teal-700', words: ['der Bus', 'der Zug', 'die Bahn', 'die Straßenbahn', 'das Fahrrad', 'das Auto', 'das Taxi', 'das Flugzeug', 'der Bahnhof', 'die Haltestelle', 'die Straße', 'die Kreuzung', 'die Ampel', 'die Karte', 'das Ticket', 'der Fahrplan', 'der Koffer', 'der Weg', 'links', 'rechts', 'geradeaus', 'fahren', 'laufen', 'ankommen'] },
  { title: 'Der Körper', icon: UserRound, image: '/images/vocab-body.png', color: 'bg-pink-50 text-pink-700', words: ['der Kopf', 'das Gesicht', 'das Auge', 'das Ohr', 'die Nase', 'der Mund', 'der Zahn', 'der Hals', 'die Schulter', 'der Arm', 'die Hand', 'der Finger', 'der Bauch', 'der Rücken', 'das Bein', 'das Knie', 'der Fuß', 'das Herz', 'die Haut', 'die Haare', 'gesund', 'krank', 'weh tun', 'helfen'] },
  { title: 'Kleidung', icon: Library, image: '/images/vocab-shopping.png', color: 'bg-amber-50 text-amber-700', words: ['das Hemd', 'die Bluse', 'das T-Shirt', 'der Pullover', 'die Jacke', 'der Mantel', 'die Hose', 'der Rock', 'das Kleid', 'die Jeans', 'der Schuh', 'die Socke', 'der Hut', 'die Mütze', 'der Schal', 'der Gürtel', 'die Tasche', 'die Brille', 'rot', 'blau', 'groß', 'klein', 'tragen', 'anziehen'] },
  { title: 'Wetter & Jahreszeiten', icon: Library, image: '/images/vocab-weather.png', color: 'bg-cyan-50 text-cyan-700', words: ['die Sonne', 'die Wolke', 'der Regen', 'der Schnee', 'der Wind', 'der Sturm', 'der Himmel', 'der Regenschirm', 'der Frühling', 'der Sommer', 'der Herbst', 'der Winter', 'warm', 'kalt', 'regnen'] },
  { title: 'Familie & Menschen', icon: UserRound, image: '/images/vocab-family.png', color: 'bg-red-50 text-red-700', words: ['die Familie', 'die Mutter', 'der Vater', 'das Kind', 'das Baby', 'der Freund', 'die Freundin', 'der Nachbar', 'die Nachbarin', 'die Großmutter', 'der Großvater', 'der Geburtstag', 'besuchen', 'sprechen'] },
  { title: 'Freizeit', icon: Library, image: '/images/vocab-free-time.png', color: 'bg-lime-50 text-lime-700', words: ['die Musik', 'der Fußball', 'das Schwimmen', 'das Wandern', 'der Film', 'die Kamera', 'das Kochen', 'das Zeichnen', 'das Tanzen', 'der Park', 'spielen', 'hören'] },
  { title: 'Restaurant & Café', icon: Utensils, image: '/images/vocab-restaurant.png', color: 'bg-stone-50 text-stone-700', words: ['das Restaurant', 'das Café', 'der Kellner', 'die Speisekarte', 'die Reservierung', 'das Frühstück', 'das Mittagessen', 'das Abendessen', 'der Nachtisch', 'bestellen', 'servieren'] },
];

interface VocabularyPageProps { languageMode: LanguageMode }

export const VocabularyPage: React.FC<VocabularyPageProps> = ({ languageMode }) => {
  const [playingTitle, setPlayingTitle] = useState<string | null>(null);
  const getTranslation = (word: string) => {
    if (languageMode === 'none') return '';
    const item = translations[word];
    if (languageMode === 'en') return item?.en || englishTranslations[word] || '';
    return item ? item[languageMode] : '';
  };
  const playGroup = (title: string, words: string[]) => {
    if (playingTitle === title) { stopSpeech(); setPlayingTitle(null); return; }
    setPlayingTitle(title);
    speakGerman(words.join('. '), () => setPlayingTitle(null));
  };
  return (
  <div className="min-h-screen bg-[#f7f8fa] text-slate-900 font-reading">
    <header className="sticky top-0 z-30 border-b border-slate-200/80 bg-white/95 backdrop-blur-md"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-3 sm:px-8"><a href="/kurs" className="flex items-center gap-3" aria-label="Zum Kurs"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-slate-900 text-sm font-black text-white">DE</span><span className="hidden sm:block"><span className="block text-sm font-extrabold tracking-tight">Deutsch Lernen</span><span className="block text-[11px] font-medium text-slate-500">Wortschatz kompakt</span></span></a><nav className="flex items-center gap-2" aria-label="Hauptnavigation"><a href="/kurs" className="inline-flex items-center gap-2 rounded-xl px-3.5 py-2 text-xs font-bold text-slate-600 transition hover:bg-slate-100"><ArrowLeft className="h-4 w-4" /><span className="hidden sm:inline">Zum Kurs</span></a><a href="/geschichten" className="inline-flex items-center gap-2 rounded-xl px-3.5 py-2 text-xs font-bold text-slate-600 transition hover:bg-slate-100"><BookOpen className="h-4 w-4" /><span className="hidden sm:inline">Geschichten</span></a></nav></div></header>
    <main className="mx-auto max-w-7xl px-4 py-8 sm:px-8 lg:px-12"><div className="mb-7 flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-indigo-600">Wortschatz</p><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Deutsch für jeden Tag</h1><p className="mt-2 text-sm text-slate-500">Über 190 wichtige Wörter — schnell finden, sehen und merken.</p></div><span className="hidden rounded-full bg-white px-3 py-1.5 text-xs font-bold text-slate-500 shadow-sm sm:inline-flex">9 Themen · 192 Wörter</span></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{groups.map(({ title, icon: Icon, image, color, words }) => <section key={title} className="overflow-hidden rounded-3xl border border-slate-200/80 bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><img src={image} alt="" className="h-44 w-full object-cover object-center" /><div className="p-5"><div className="mb-4 flex items-center justify-between gap-3"><div className="flex items-center gap-3"><span className={`flex h-10 w-10 items-center justify-center rounded-2xl ${color}`}><Icon className="h-5 w-5" /></span><h2 className="text-lg font-extrabold">{title}</h2></div><button type="button" onClick={() => playGroup(title, words)} className={`inline-flex items-center gap-1.5 rounded-xl px-2.5 py-2 text-xs font-bold transition ${playingTitle === title ? 'bg-indigo-600 text-white' : 'bg-slate-100 text-slate-700 hover:bg-indigo-50 hover:text-indigo-700'}`} aria-label={`${title} anhören`} title={`${title} anhören`}>{playingTitle === title ? <Pause className="h-3.5 w-3.5 fill-current" /> : <Volume2 className="h-3.5 w-3.5" />}<span>{playingTitle === title ? 'Pause' : 'Audio'}</span></button></div><div className="grid grid-cols-2 gap-x-4 gap-y-2">{words.map((word) => <span key={word} className="border-b border-slate-100 pb-1"><span className="block text-sm font-medium text-slate-700">{word}</span>{languageMode !== 'none' && <span className="mt-0.5 block truncate text-[11px] font-medium text-slate-400" dir={languageMode === 'ar' ? 'rtl' : 'ltr'}>{getTranslation(word)}</span>}</span>)}</div></div></section>)}</div></main>
  </div>
  );
};
