import React from 'react';
import { ArrowLeft, BookOpen, BriefcaseBusiness, Carrot, GraduationCap, Home, Library, ShoppingBasket, TramFront, UserRound, Utensils } from 'lucide-react';

const groups = [
  { title: 'Im Büro', icon: BriefcaseBusiness, image: '/images/vocab-office.png', color: 'bg-indigo-50 text-indigo-700', words: ['der Schreibtisch', 'der Computer', 'der Bildschirm', 'die Tastatur', 'die Maus', 'der Drucker', 'das Papier', 'der Ordner', 'die Datei', 'das Dokument', 'das Telefon', 'die E-Mail', 'der Termin', 'die Besprechung', 'der Kalender', 'der Kollege', 'die Kollegin', 'der Chef', 'die Abteilung', 'die Pause', 'arbeiten', 'schreiben', 'drucken', 'telefonieren'] },
  { title: 'Essen & Trinken', icon: Utensils, image: '/images/vocab-food.png', color: 'bg-orange-50 text-orange-700', words: ['das Brot', 'das Brötchen', 'der Käse', 'die Butter', 'die Suppe', 'der Reis', 'die Nudeln', 'das Fleisch', 'der Fisch', 'das Ei', 'das Gemüse', 'der Salat', 'das Wasser', 'die Milch', 'der Saft', 'der Kaffee', 'der Tee', 'der Zucker', 'das Salz', 'der Teller', 'die Gabel', 'das Messer', 'essen', 'trinken'] },
  { title: 'Obst', icon: Carrot, image: '/images/vocab-fruit.png', color: 'bg-rose-50 text-rose-700', words: ['der Apfel', 'die Banane', 'die Orange', 'die Mandarine', 'die Birne', 'die Traube', 'die Erdbeere', 'die Zitrone', 'die Kirsche', 'der Pfirsich', 'die Melone', 'die Wassermelone', 'die Ananas', 'die Mango', 'die Kiwi', 'die Feige', 'die Pflaume', 'die Himbeere', 'die Blaubeere', 'süß', 'frisch', 'reif', 'schälen', 'schneiden'] },
  { title: 'In der Schule', icon: GraduationCap, image: '/images/vocab-school.png', color: 'bg-sky-50 text-sky-700', words: ['die Schule', 'die Klasse', 'der Lehrer', 'die Lehrerin', 'der Schüler', 'die Schülerin', 'das Buch', 'das Heft', 'der Stift', 'der Bleistift', 'der Radiergummi', 'das Lineal', 'der Rucksack', 'die Tafel', 'der Tisch', 'der Stundenplan', 'die Aufgabe', 'die Hausaufgabe', 'die Prüfung', 'die Note', 'lernen', 'lesen', 'schreiben', 'rechnen'] },
  { title: 'Zu Hause', icon: Home, image: '/images/vocab-home.png', color: 'bg-emerald-50 text-emerald-700', words: ['das Haus', 'die Wohnung', 'das Zimmer', 'das Wohnzimmer', 'das Schlafzimmer', 'die Küche', 'das Bad', 'der Flur', 'der Balkon', 'der Tisch', 'der Stuhl', 'das Bett', 'der Schrank', 'das Sofa', 'die Lampe', 'der Fernseher', 'der Kühlschrank', 'die Waschmaschine', 'die Tür', 'das Fenster', 'der Schlüssel', 'putzen', 'kochen', 'wohnen'] },
  { title: 'Einkaufen', icon: ShoppingBasket, image: '/images/vocab-shopping.png', color: 'bg-violet-50 text-violet-700', words: ['der Laden', 'der Supermarkt', 'der Markt', 'das Geschäft', 'der Preis', 'das Geld', 'die Kasse', 'der Einkaufswagen', 'der Korb', 'die Tasche', 'der Beutel', 'der Bon', 'die Rechnung', 'die Karte', 'das Angebot', 'die Größe', 'die Farbe', 'die Kleidung', 'der Kunde', 'die Kundin', 'kaufen', 'bezahlen', 'kosten', 'suchen'] },
  { title: 'Unterwegs', icon: TramFront, image: '/images/vocab-transport.png', color: 'bg-teal-50 text-teal-700', words: ['der Bus', 'der Zug', 'die Bahn', 'die Straßenbahn', 'das Fahrrad', 'das Auto', 'das Taxi', 'das Flugzeug', 'der Bahnhof', 'die Haltestelle', 'die Straße', 'die Kreuzung', 'die Ampel', 'die Karte', 'das Ticket', 'der Fahrplan', 'der Koffer', 'der Weg', 'links', 'rechts', 'geradeaus', 'fahren', 'laufen', 'ankommen'] },
  { title: 'Der Körper', icon: UserRound, image: '/images/vocab-body.png', color: 'bg-pink-50 text-pink-700', words: ['der Kopf', 'das Gesicht', 'das Auge', 'das Ohr', 'die Nase', 'der Mund', 'der Zahn', 'der Hals', 'die Schulter', 'der Arm', 'die Hand', 'der Finger', 'der Bauch', 'der Rücken', 'das Bein', 'das Knie', 'der Fuß', 'das Herz', 'die Haut', 'die Haare', 'gesund', 'krank', 'weh tun', 'helfen'] },
  { title: 'Kleidung', icon: Library, image: '/images/vocab-shopping.png', color: 'bg-amber-50 text-amber-700', words: ['das Hemd', 'die Bluse', 'das T-Shirt', 'der Pullover', 'die Jacke', 'der Mantel', 'die Hose', 'der Rock', 'das Kleid', 'die Jeans', 'der Schuh', 'die Socke', 'der Hut', 'die Mütze', 'der Schal', 'der Gürtel', 'die Tasche', 'die Brille', 'rot', 'blau', 'groß', 'klein', 'tragen', 'anziehen'] },
];

export const VocabularyPage: React.FC = () => (
  <div className="min-h-screen bg-[#f7f8fa] text-slate-900 font-reading">
    <header className="sticky top-0 z-30 border-b border-slate-200/80 bg-white/95 backdrop-blur-md"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-3 sm:px-8"><a href="/kurs" className="flex items-center gap-3" aria-label="Zum Kurs"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-slate-900 text-sm font-black text-white">DE</span><span className="hidden sm:block"><span className="block text-sm font-extrabold tracking-tight">Deutsch Lernen</span><span className="block text-[11px] font-medium text-slate-500">Wortschatz kompakt</span></span></a><nav className="flex items-center gap-2" aria-label="Hauptnavigation"><a href="/kurs" className="inline-flex items-center gap-2 rounded-xl px-3.5 py-2 text-xs font-bold text-slate-600 transition hover:bg-slate-100"><ArrowLeft className="h-4 w-4" /><span className="hidden sm:inline">Zum Kurs</span></a><a href="/geschichten" className="inline-flex items-center gap-2 rounded-xl px-3.5 py-2 text-xs font-bold text-slate-600 transition hover:bg-slate-100"><BookOpen className="h-4 w-4" /><span className="hidden sm:inline">Geschichten</span></a></nav></div></header>
    <main className="mx-auto max-w-7xl px-4 py-8 sm:px-8 lg:px-12"><div className="mb-7 flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-indigo-600">Wortschatz</p><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Deutsch für jeden Tag</h1><p className="mt-2 text-sm text-slate-500">Über 190 wichtige Wörter — schnell finden, sehen und merken.</p></div><span className="hidden rounded-full bg-white px-3 py-1.5 text-xs font-bold text-slate-500 shadow-sm sm:inline-flex">9 Themen · 192 Wörter</span></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{groups.map(({ title, icon: Icon, image, color, words }) => <section key={title} className="overflow-hidden rounded-3xl border border-slate-200/80 bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><img src={image} alt="" className="h-44 w-full object-cover object-center" /><div className="p-5"><div className="mb-4 flex items-center gap-3"><span className={`flex h-10 w-10 items-center justify-center rounded-2xl ${color}`}><Icon className="h-5 w-5" /></span><h2 className="text-lg font-extrabold">{title}</h2></div><div className="grid grid-cols-2 gap-x-4 gap-y-2">{words.map((word) => <span key={word} className="border-b border-slate-100 pb-1 text-sm font-medium text-slate-700">{word}</span>)}</div></div></section>)}</div></main>
  </div>
);
